# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ba8576dbc8cf0ef66f983a60445ae09556759aa51822ee0a62d177844f0722fb5a2328db36210e74af37a366f05564ca2380c4e66af918f27a1d4631ee7713

test:
  secret_key_base: 8059f165956d35299466d6d2de1981b59d1f787a6342d6afaa29fd6632ed3fb527350fd94d1a8ba1f9ce9f477f4f0e767980dc9dba8cb2fe446a3de732af24ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
